import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './page.module.scss'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Goldener Pfau',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} background-site`}>
        <main className="no-spacing">{children}</main>
      </body>
    </html>
  )
}
